### ISSUE TITLE
Add CSS classes to make formatting messages easier

### ISSUE THREAD

**Issue by adammathys** [StemboltHQ/imperilment#38]
We semi-regularly need to be able to enter lower-case and super-script text for the answers. Having two CSS classes would make this significantly easier, as we wouldn't need to in-line the styles everywhere.

``` css
.lower {
  text-transform: lowercase;
}
.super {
  font-size: 0.5em;
  vertical-align: super;
}
```

![text](https://cloud.githubusercontent.com/assets/876067/16589443/0d4dab2e-4288-11e6-9752-3db7a6bd11ad.png)
